### PR TITLE
Theme

### PR DESCRIPTION
**Pull request by lauraselby**
## Overview of changes

Tried adding a Mantine theme. Only really focuses on index page so far, still need to adapt it to other pages.

## Checklist

- [x] I have tested these changes locally using `npm run test`
- [x] I have updated the documentation (if needed)
- [x] I have added or updated tests for these changes (if applicable)

### CODE REVIEW

**Comment by cjrace** [comment]
Still to do:

- [ ] Pull new theme through into all other pages

- [ ] Shuffle / centre homepage components (currently a bit wonky!)

image

- [ ] Change button text in dark mode hover to give enough contrast

image

- [ ] Add more contrast into the dropdown for cocktails on dark mode 

image

**Comment by lauraselby** [comment]
I've since added a bunch more to this. 

Holidays page, breadcrumbs and using page / main divs consistently across each sub page (we were on some but not others previously)

**Comment by lauraselby** [comment]
I think the theme is pulling into all pages, atm all it does is set primary colour and formats buttons but that seems to be happening across all without importing the theme specifically (maybe cos it's on the app file?)

**Comment by cjrace** [comment]
Rebased this branch and resolved conflicts to main, fixed up a couple of small things along the way and then raised the following milestone with some quick follow up issues to do after we've merged this into main (best to get this branch this sooner rather than later to avoid any more conflicts) - https://github.com/cjrace/almostyellow/milestone/1

**Pull request merged**
